apiVersion: v1
kind: Pod
metadata:
    name: pod-webapp
    namespace: webapp
spec:
    containers:
      - name: aliya-webapp
        image: 637338645550.dkr.ecr.us-east-1.amazonaws.com/aliya-webapp:v0.1
        env:
          - name: DBPWD
            value: pwd916
          - name: DBUSER
            value: root
          - name: DBHOST
            value: "mysql.database.svc.cluster.local"
          - name: DBPORT
            value: "3306"
        ports:
          - containerPort: 8080
