apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicas
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: aliya-webapp
        image: 637338645550.dkr.ecr.us-east-1.amazonaws.com/aliya-webapp:v0.1
        env:
          - name: DBPWD
            value: pwd916
          - name: DBUSER
            value: root
          - name: DBHOST
            value: "10.244.0.5"
          - name: DBPORT
            value: "3306"
        ports:
          - containerPort: 8080
